//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Box : IMovable
{
	public bool StandsOnGoal { get; set; }
	public Color Color {get; set; }
	public Square Square { get; set; }

	public bool CanBeMoved()
	{
		throw new System.NotImplementedException();
	}

    public void Move()
    {
        throw new NotImplementedException();
    }
}

