//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Box
{
	public virtual object StandsOnGoal { get; set; }

	public virtual Color Color {get; set; }

	public virtual Square Square { get; set; }

	public virtual bool CanBeMoved()
	{
		throw new System.NotImplementedException();
	}
}

