//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class GoalSquare : Square
{
    public GoalSquare(int row, int column)
        : base(row, column)
    {
        base.Available = true;
    }
    public override void print()
    {
        if (this.Player == null && Box == null)
            Console.Write("x");
        else if (Box != null)
            Console.Write("0");
        else
            Console.Write("@");
    }
}