//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Player : IMovable
{
    public Square Square { get; set; }

    public void Stop()
    {
        throw new System.NotImplementedException();
    }

    public void ResetPuzzle()
    {
        throw new System.NotImplementedException();
    }

    public void Move()
    {
        throw new NotImplementedException();
    }
}

