//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class PlayGround
{
	public virtual IEnumerable<Box> Box { get; set; }

	public virtual Player Player { get; set; }

	public virtual IEnumerable<Square> Square { get; set; }

	public virtual void CheckLevelCompleted()
	{
		throw new System.NotImplementedException();
	}

	public virtual void ResetPuzzle()
	{
		throw new System.NotImplementedException();
	}

	public virtual void CheckMoveValid()
	{
		throw new System.NotImplementedException();
	}

	public virtual void GenerateLevel(int level)
	{
		throw new System.NotImplementedException();
	}

	public virtual void MovePlayer()
	{
		throw new System.NotImplementedException();
	}

}

