//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;

public abstract class Square
{
    // Properties
    public int Row { get; set; }
    public int Column { get; set; }
    public bool Available { get; set; }
    public Box Box { get; set; }
    public Player Player { get; set; }

    // Constructor
    public Square(int row, int column)
    {
        Row = row;
        Column = column;
        Available = true;
    }

    //Return the Row and Column in string format, like "1:15"
    public string ID
    {
        get
        {
            return Row + ":" + Column;
        }
    }

    public bool addBox(Box box) // returns whether placing a box was succeeded
    {
        if (Available)
        {
            this.Box = box;
            return true; // box is placed
        }
        else
            return false; // square was not available
    }

    public virtual void RemoveMovableObject()
    {
        Box = null;
        Player = null;
    }

    public abstract void print();
}

