//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Square
{
	public virtual object Available { get; set; }
	public virtual object Row { get; set; }
	public virtual object Column { get; set; }

	public virtual void AddBox()
	{
		throw new System.NotImplementedException();
	}

	public virtual void RemoveBox()
	{
		throw new System.NotImplementedException();
	}
}

