//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class GameController
{
	public virtual PlayGround PlayGround { get; set; }

	public virtual Game Game { get; set; }

	public virtual SocobanPresentation SocobanPresentation { get; set; }
}

